apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "auto-resize.fullname" . }}
  labels: {{- include "auto-resize.labels" . | nindent 4 }}
rules:
  - resources: ["statefulsets"]
    verbs: ["get", "list", "patch", "watch"]
    apiGroups: ["apps"]
  - resources: ["pods"]
    verbs: ["get"]
    apiGroups: [""]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["get", "create"]
