apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "rso-webhook-server.fullname" . }}
webhooks:
- name: {{ .Values.mutatingwebhookconfiguration.name }}
  sideEffects: None
  admissionReviewVersions: ["v1", "v1beta1"]
  # namespaceSelector:
  #   matchExpressions:
  #   - key: kubernetes.io/metadata.name
  #     operator: In
  #     values: ["intern-dev"]
  rules:
  - operations: ["UPDATE"]
    apiGroups: ["apps"]
    apiVersions: ["v1"]
    resources: ["statefulsets"]
  clientConfig:
    service:
      name: webhook
      namespace: {{ .Release.Namespace }}
      path: "/mutating"
      port: 443
    caBundle: {{ required "tls.caBundle must contain the base64-encoded CA certificate" .Values.tls.caBundle | quote }}